server:
  port: 8083
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://sowjanya:sowjanya@cluster0.rwz4p.mongodb.net/customers?retryWrites=true&w=majority
      
  application:
    name: CUSTOMER-SERVICE
